### PR TITLE
Fixing interpolation of null

### LINKED ISSUE #74: Support a `null` literal
JSON defines `null`, but the expression language does not support it.

### PR DESCRIPTION
**Pull request by TheNavigat**
Resolves #74

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -20,7 +20,19 @@ let interpolate = (string, context) => {
...
       throw new TemplateError('cannot interpolate array/object: ' + string);
     }
-    result += remaining.slice(0, offset) + v.result.toString();
+
+    result += remaining.slice(0, offset);
+
+    // We can't use JSON.stringify(), which would parse null correctly,
+    // because it ignores double quotes in strings. For example,
+    // JSON.stringify('hello "world"') will return 'hello world' instead of
+    // 'hello "world"'
```
Comment (djmitche) [inline src/index.js]:
```
> JSON.stringify('hello "world"')
'"hello \\"world\\""'
```
I think this implementation is correct, but the comment isn't..
